/* eslint-disable no-unused-vars */
export enum UserSettingsChannels {
  SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS',
  LOAD_USER_SETTINGS = 'LOAD_USER_SETTINGS',
  RESET_USER_SETTINGS = 'RESET_USER_SETTINGS',
  SELECT_GIT_PROJECTS_PATH = 'SELECT_GIT_PROJECTS_PATH',
  SELECT_GIT_CONFIG_FILE_PATH = 'SELECT_GIT_CONFIG_FILE_PATH',
  SELECT_SSH_CONFIG_FILE_PATH = 'SELECT_SSH_CONFIG_FILE_PATH',
}
