name: Release new version
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: '18'
      - run: yarn --frozen-lockfile
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
        run: npx semantic-release
