name: Release new version
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          persist-credential: false
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: '18'
      - run: yarn --frozen-lockfile
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
        run: npx semantic-release
